# Voice Assistant Service Configuration

service:
  name: "voice-assistant"
  host: "0.0.0.0"
  port: 10300

# Ollama Model Configuration
models:
  # Intent Classifier (ultra-fast routing)
  classifier:
    name: "llama3.2:1b"
    temperature: 0.1
    max_tokens: 5
  
  # Home Assistant Control Agent
  home_assistant:
    name: "llama3.2:3b"
    temperature: 0.3
    max_tokens: 50
  
  # Conversation Agent
  conversation:
    name: "qwen2.5:7b"
    temperature: 0.7
    max_tokens: 100
  
  # Tool Execution Agent (loaded on-demand)
  tools:
    name: "qwen2.5:14b"
    temperature: 0.5
    max_tokens: 200

# Audio Settings
audio:
  sample_rate: 16000
  channels: 1
  chunk_size: 1024

# Whisper Transcription Settings
whisper:
  beam_size: 1
  vad_filter: true
  min_silence_duration_ms: 500

# Intent Classification Cache
# Fast pattern matching for common phrases
intent_cache:
  # Home Control
  "turn on": "HOME_CONTROL"
  "turn off": "HOME_CONTROL"
  "set": "HOME_CONTROL"
  "dim": "HOME_CONTROL"
  "brighten": "HOME_CONTROL"
  "lights": "HOME_CONTROL"
  "temperature": "HOME_CONTROL"
  "thermostat": "HOME_CONTROL"
  "lock": "HOME_CONTROL"
  "unlock": "HOME_CONTROL"
  
  # Tool Execution
  "send": "TOOLS"
  "email": "TOOLS"
  "check email": "TOOLS"
  "read email": "TOOLS"
  "create event": "TOOLS"
  "calendar": "TOOLS"
  "set timer": "TOOLS"
  "set alarm": "TOOLS"
  "remind me": "TOOLS"
  "schedule": "TOOLS"
  "contact": "TOOLS"
  
  # Conversation
  "what is": "CONVERSATION"
  "who is": "CONVERSATION"
  "tell me": "CONVERSATION"
  "how do": "CONVERSATION"
  "why": "CONVERSATION"
  "when": "CONVERSATION"
  "where": "CONVERSATION"

# Home Assistant Device Configuration
home_assistant:
  enabled: true
  devices:
    lights:
      - living_room_light
      - bedroom_light
      - kitchen_light
      - bathroom_light
    climate:
      - home_thermostat
    switches:
      - coffee_maker
      - fan

# Performance Settings
performance:
  max_concurrent_requests: 3
  request_timeout: 30
  transcription_timeout: 10
